name: Docker Image CI

on:  
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +%s)"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag discord-bot:${{ steps.date.outputs.date }}

    - name: Build the Docker image
      run: docker run --env DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} --env DOTNET_ENVIRONMENT=Release discord-bot:${{ steps.date.outputs.date }}       
